// new Vue({
//     el: '#app',
//     data: {
//       ingredient: ''
//     },
//     methods:{
//     listIngredientPairings: function(response, ingredient) {
//         // alert("hi");
//       // GET request
//       this.$http({url: lookup, method: 'GET'}).then(function (response) {
//         console.log("******RESPONSE*****");
//         console.log(response);
//           // success callback
//       }, function (response) {
//         console.log(response);
//           // error callback
//       });
//
//     }
//   }
//
// })

// var lookup = require('../data/ingredients');

new Vue({

  el: '#app',
  data: {
    ingredient: ''
  },
  methods: {
    // listIngredientPairings: function(){
    //   alert("HI");
    // }
    listIngredientPairings: function(data, ingredient){
      // this.$http.get(lookup, function(data, key, ingredient){
      var data = {
        "Almonds": ["apples", "apricots", "caramel", "chocolate", "cononut", "cream", "plums", "prunes", "raisins", "rice", "strawberries"],
        "Anchovies": ["eggs", "hard boiled eggs", "garlic", "lemon", "olives", "onions", "parsley"],
        "Apples": ["almonds","bacon", "blackberries", "blue cheese", "brandy", "brown sugar", "butter", "black pepper", "butterscotch", "caramel", "celery", "cheese", "cinnamon", "cloves", "cognac", "coriander", "cranberries", "cream", "currants", "custard", "dates", "ginger", "Grand Marnier", "hazelnuts", "honey", "horseradish", "maple syrup", "molasses", "nutmeg", "nuts", "oatmeal", "oranges", "pears", "pistachios", "praline", "prunes", "raisins", "rosemary", "rum", "sauerkraut", "sausages", "sherry", "sour cream", "sugar", "vanilla", "vermouth", "vinegar", "walnuts", "wine", "yogurt"],
        "Apricots": ["almonds", "brandy", "caramel", "cherries", "coconut", "cognac", "cream", "custard", "ginger", "Grand Marnier", "hazelnuts", "honey", "lamb", "lemon", "lime", "maple syrup", "nectarines", "oranges", "peaches", "pineapple", "pistachios", "plums", "raspberries", "rice", "sesame", "sour cream", "strawberries", "tarragon", "vanilla", "yougurt", "wine"],
        "Artichokes": ["aioli", "anchovies", "bacon", "basil", "bay leaves", "bread crumbs", "butter", "goat cheese", "chervil", "cream", "cumin", "fennel", "garlic", "hazelnuts", "hollandaise sauce", "lemon", "mayonnaise", "Mornay sauce", "mushrooms", "olive oil", "onions", "parmesan cheese", "parsley", "pepper", "remoulade sauce", "salt", "sausage", "thyme", "tomatoes", "white truffles", "white wine"],
        "Arugula": ["avocado", "butter", "carpaccio", "blue cheese", "garlic", "lemon", "olive oil", "parmesan cheese", "pasta", "pears", "pecans", "potatoes", "ravioli", "walnuts"],
        "Asparagus": ["anchovies", "bread crumbs", "butter", "cheese sauce", "chervil", "chives", "crabmeat", "cream", "eggs", "garlic", "ginger", "hollandaise sauce", "horseradish", "lemon", "mayonnaise", "morels", "Mornay sauce", "mushrooms", "mustard", "new potatoes", "nutmeg", "offal", "olive oil", "onion", "orange", "pancetta", "parmesan cheese", "parsley", "pepper", "rosemary", "shallots", "soy", "veloute sauce", "vinaigrette"],
        "Avocados": ["basil", "beef", "bread", "chiles", "chives", "cilantro", "crab", "cucumber", "garlic", "grapefruit", "leeks", "lemon", "lemongrass", "lime", "mangoes", "mint", "onions", "oranges", "parsley", "pineapples", "pistachios", "salt", "shrimp", "smoked fish", "sugar", "tomatillos", "tomatoes", "vinaigrette", "vinegar"],
        "Bananas": ["alcohol", "almonds", "apricots", "Armangnac", "bacon", "blueberries", "brandy", "brown sugar", "butter", "Calvados", "caramel", "cardamom", "chicken", "chocolate", "cinnamon", "coconut", "Cognac", "coriander", "cream", "cream cheese", "custard", "eggs", "fruits", "gin", "ginger", "honey", "ice cream", "Kirsch", "lemon", "lime", "malt", "maple syrup", "nuts", "oranges", "passion fruit", "pecans", "pineapples", "pralines", "raspberries", "rum", "sour cream", "strawberries", "sugar", "vanilla", "yogurt"],
        "Barley": ["almonds", "cabbage", "ham", "mushrooms", "onions", "parsley", "peas"],
        "Bass": ["almonds", "anchovies", "artichokes", "butter", "capers", "carrots", "chives", "citrus", "coriander", "fennel", "garlic", "ginger", "leeks", "lemon", "mint", "mushrooms", "olive oil", "oranges", "peppers", "potatoes", "shallots", "thyme", "tomatoes", "red wine"],
        "Bean Sprouts": ["ginger", "sesame oil", "soy sauce", "vinegar"],
        "Beef": ["basil", "beer", "bearnaise sauce", "black pepper","bordelaise sauce", "Burgundy", "carrots", "chiles", "chives", "corn", "hazelnuts", "horseradish", "Madeira", "marrow", "mushrooms", "mustard", "onions", "orange", "parsley", "peppers", "potatoes", "prunes", "scallions", "shallots", "soy", "vinegar", "wine"],
        "Beef Heart": ["bacon", "horseradish", "marjoram", "paprika", "parsley", "rosemary"],
        "Beef Ribs": ["ginger", "horseradish", "mustard", "potatoes", "tomatoes"],
        "Beet Greens":["anchovies", "butter", "horseradish", "mustard", "sour cream"],
        "Beets": ["allspice", "anchovies", "apples", "bacon", "bechamel sauce", "brown sugar", "butter", "cheese", "chives", "cloves", "cream", "creme fraiche", "cucumber", "curry", "dill", "eggs", "fennel", "ginger", "horseradish", "lemon", "mache", "mustard", "nutmeg", "onions", "oranges", "paprika", "parsley", "potatoes", "prosciutto", "salt", "shallots", "smoked fish", "sour cream", "tarragon", "vinaigrette", "vinegar", "walnuts", "watercress"],
        "Berries": ["brown sugar", "cream", "Framboise", "maple syrup", "peaches", "raspberries", "strawberries", "sugar"],
        "Black Beans": ["avocados", "bacon", "cheese", "chiles", "chives", "cilantro", "coriander", "cumin", "creme fraiche", "garlic", "ham hocks", "jalapenos", "Maderia", "mint", "onions", "oranges", "peppers", "rice", "sour cream", "tequila", "tomatoes"],
        "Blueberries":["apples", "apricots", "blue cheese", "bourbon", "brown sugar", "cinnamon", "cognac", "cream", "currants", "custard", "ginger", "Grand Marnier", "honey", "lavender", "lemon", "lime", "maple syrup", "peaches", "pineapple", "raspberries", "sugar", "thyme", "yogurt"],
        "Broccoli": ["anchovies", "bacon", "bread crumbs", "butter", "cheese", "cream", "cumin", "garlic", "hollandaise sauce", "lemon", "Maltaise sauce", "nuts", "olive oil", "onions", "orange", "peppers", "pimiento", "potatoes", "vinaigrette", "watercress"],
        "Broccoli Rabe": ["garlic", "lemon", "olive oil", "red pepper flakes", "romano cheese"],
        "Brussels Sprouts": ["almonds", "anchovies", "apples", "bacon", "bread crumbs", "butter", "carrots", "cheese", "chestnuts", "cream", "duck fat", "eggs", "garlic", "grapefruit", "ham", "hollandaise sauce", "lemon", "mushrooms", "mustard", "nutmeg", "onions", "pancetta", "parsley", "pepper", "rosemary", "salt", "sweet peppers", "rosemary", "thyme", "vinegar", "walnuts"],
        "Bulgar": ["lemon", "mint", "olive oil", "onions", "parsley"],
        "Cabbage": ["apples", "bacon", "bechamel sauce", "beets", "butter", "caraway seeds", "caviar", "chestnuts", "conocut", "cream", "garlic", "ham ", "horseradish", "leeks", "lemon", "juniper berries", "Maderia", "mustard", "nutmeg", "onions", "paprika", "parsley", "pepper", "poppy seeds", "potatoes", "salt", "sausages", "sorrel", "spinach", "vinegar" ],
        "Carrots": ["almonds", "bacon", "basil", "beef", "brandy", "butter", "cayenne", "celery", "cheese", "chervil", "chives", "cilantro", "cinnamon", "cloves", "cream", "cumin", "dill", "fennel", "garlic", "honey", "lemon", "Maderia", "maple syrup", "marjoram", "Marsala", "mayonnaise", "mint", "mushrooms", "mustard", "nutmeg", "nuts", "olive oil", "olives", "onions", "oranges", "paprika", "parsley", "peas", "pine nuts", "potatoes", "raisins", "rosemary", "sage", "shallots", "stock", "sugar", "tarragon", "thyme", "tomatoes", "turnips", "vinegar", "walnuts"],
        "Catfish": ["bacon", "capers", "ginger", "ketchup", "mustard", "olive oil", "olives", "pecans", "peppers"],
        "Cauliflower": ["aioli", "almonds", "anchovies", "bacon", "bechamel sauce", "bread crumbs", "butter", "cheddar cheese", "parmesan cheese", "chervil", "chives", "cracker crumbs", "cream", "creme fraiche", "currry", "garlic", "ham", "hollandaise sauce", "lemon", "Mornay sauce", "mousseline sauce", "mushrooms", "mussels", "nutmeg", "nuts", "olive oil", "parsley", "pepper", "tomato sauce", "walnuts"],
        "Caviar": ["blini", "bread", "cream", "lemon", "parsley", "potatoes", "shallots", "smoked salmon", "sour cream", "toast", "vodka"],
        "Celery": ["almonds", "bechamel sauce", "blue cheese", "bread crumbs", "butter", "celery seeds", "cream", "curry", "dill", "fennel", "hollandaise sauce", "lemon", "nutmeg", "parsley", "walnuts"],
        "Celery Root": ["bacon", "bread crumbs", "butter", "caraway seeds", "parmesan cheese", "swiss cheese", "cream", "fennel", "garlic", "hollandaise sauce", "lemon", "mayonnaise", "mustard", "nutmeg", "olive oil", "onions", "parsley", "potatoes", "butternust squash", "thyme", "vinegar", "walust"],
        "Chanterelles": ["bechamel sauce", "butter", "chervil", "chicken", "cream", "creme fraiche", "egges", "fish", "game", "garlic", "herbs", "leeks", "lemon", "olive oil", "parsley", "black pepper", "rabbit", "shallots", "shellfish", "tarragon", "veal", "vinaigrette"],
        "Chard": ["lemon", "peppers", "saffron"],
        "Cherries": ["almonds", "apricots", "Armangnac", "brandy", "caramel", "chocolate", "Cognac", "cream", "currants", "custards", "goat cheese", "Grand Marnier", "ice cream", "Kirsch", "lemon", "mint", "nectarines", "nuts", "peaches", "black pepper", "plums", "port", "sour cream", "verbena", "vanilla", "zabaione"],
        "Chestnuts": ["apples", "brandy", "brown sugar", "brussels sprouts", "butter", "cabbage", "carrots", "cayenne", "celery", "Chartreuse", "chocolate",  "cinnamon", "cloves", "cognac", "cream", "creme fraiche", "fennel", "ginger", "lemon", "Marsala", "mushrooms", "onions", "orange", "parsley", "prunes", "raspberries", "rum", "stuffing", "sugar", "vinegar"],
        "Chick Peas": ["carrots", "cilantro", "coriander", "couscous", "cumin", "garlic", "lemon", "mint", "olive oil", "onions", "parsley", "peppers", "rosemary", "spinach", "tahini", "tomatoes", "yogurt"],
        "Chicken": ["achiote", "almonds", "apples", "Armangnac", "asparagus", "bacon", "barbecue sauce", "basil", "beer", "bearnaise sauce", "blood", "brandy", "bread crumbs", "cabbage", "Calvados", "champagne", "cheese", "cherries", "chervil", "chestnuts", "chives", "cider", "coconut", "Cognac", "coriander", "corn", "cranberries", "cream", "curry", "dill", "endive", "escarole", "fennel", "five-spice powder", "foie gras", "Fontina cheese", "garlic", "ginger", "gochi berries", "grapes", "herbs", "honey", "horseradish", "lemon", "lime", "Maderia", "mangoes", "marjoram", "mint", "morels", "musgrooms", "mustard", "mussels", "nutmeg", "olive oil", "olives", "onions", "oranges", "oregano", "oysters", "paprika", "parmesan cheese", "parsley", "peas", "pecans", "pepper", "pineapples", "plums", "prunes", "Riesling", "rosemary", "sour cream", "soy sauce", "star anise", "sweetbreads", "sweet potatoes", "tarragon", "teriyaki sauce", "thyme", "tomatoes", "truffles", "vinegar", "yogurt"],
        "Chicken Livers": ["bacon", "brandy", "Cognac", "cream", "garlic", "Madeira", "mushrooms", "onions", "parsley", "pepper", "salt", "sour cream"],
        "Chocolate": ["almonds", "bananas", "caramel", "cheries", "cinnamon", "citrus peel", "coffee", "coconut", "cream", "ginger", "lemon", "liquors", "malt", "maple", "mint", "nuts", "orange", "passion fruit", "pecans", "pistachios", "raspberries", "rum", "tea", "vanilla", "verbena", "violets", "walnuts"],
        "Clams": ["bacon", "bread crumbs", "butter", "chiles", "chives", "cream", "curry", "garlic", "ginger", "horseradish", "lemon", "olive oil", "onion", "paprika", "parsley", "Pernod", "potatoes", "sake", "shallots", "sour cream", "Tabasco", "tarragon", "tartar sauce", "thyme", "tomatoes", "vinegar", "wine", "worcestershire"],
        "Coconuts": ["apricots", "bananas", "chocolate", "custard", "fruits", "lime", "macadamia nuts", "nuts",  "passion fruit", "pineapple" ],
        "Cod": ["bay leaves", "black beans", "capers", "black olives", "butter", "capers", "caraway seeds", "champagne", "chervil", "coriander", "eggplant", "garlic", "ginger", "hollandaise sauce", "horseradish", "juniper berries", "leeks", "lemon", "milk", "mushrooms", "mustard", "olive oil", "olives", "onions", "parsley", "pepper", "potatoes", "rosemary", "sake", "shallots", "soy sauce", "thyme", "tomatoes", "truffles", "vinaigrette", "vinegar", "wine"],
        "Coffee": ["cinnamon", "Cognac", "cream", "hazelnut", "lemon", "vanilla" ],
        "Corn": ["bacon", "basil", "butter", "cayenne", "chanterelles", "chiles", "chives", "clinatro", "cream", "feta cheese", "garlic", "lemon", "lime", "marjoram", "onions", "parmesan cheese", "parsley", "black pepepr", "pepeprs", "salt", "scallions", "sweet pepper", "worcestershire"],
        "Corned Beef": ["beets", "cabbage", "carrots", "garlic", "horseradish", "mustard", "nutmeg", "onions", "parsley", "potatoes"],
        "Crabs": ["almonds", "avocado", "bacon", "butter", "cabbage", "celery", "chiles", "chives", "cocnut", "cognac", "coriander", "corn", "cream", "creme fraiche", "curry", "fennel seeds", "garlic", "ginger", "grapefruit", "hollandaise sauce", "leeks", "lemon", "lemongrass", "lettuce", "Maderia", "mangoes", "mayonnaise", "mornay sauce", "mushrooms", "mustard", "nutmeg", "onions", "oranges", "parsley", "black pepper", "potatoes", "remoulade", "rice", "scallions", "sherry", "sour cream", "tarragon", "Thousand Island Dressing", "Tabasco sauce", "tomatoes", "black truffles", "vinaigrette", "vinegar", "white wine", "worcestershire"],
        "Cranberries": ["apples", "cinnamon", "cloves", "oranges", "pears", "sugar", "walnuts"],
        "Crayfish": ["avocado", "basil", "bay leaves", "brandy", "bread crumbs", "butter", "carrots", "cayenne", "parmesan cheese", "Cognac", "coriander", "cream", "dill", "garlic", "hollandaise", "leeks", "lemon", "mayonnaise", "nutmeg", "onions", "parsley", "saffron", "shallots", "sherry", "sorrel", "tarragon", "thyme", "tomatoes", "truffles", "vinegar", "white wine"],
        "Cucumbers": ["anchovies", "basil", "butter", "celery seeds", "chervil", "chives", "cilantro", "cream", "cream cheese", "dill", "fennel", "Feta Cheese", "garlic", "ginger", "horseradish", "lemon", "lime", "mangoes", "mayonnaise", "mint", "mushrooms", "nutmeg", "olive oil", "onions", "parsley", "pepper", "salt", "sour cream", "strawberries", "tomatoe sauce", "tomatoes", "vinegar", "yogurt"],
        "Currants": ["almonds", "cherries", "cream", "pears", "prunes", "raspberries"],
        "Custards": ["almonds", "bananas", "berries", "caramel", "cherry", "chocolate", "cinnamon", "cononut", "coffee", "Cognac", "Cointreau", "ginger", "lemon", "maple", "Marsala", "oranges", "passion fruit", "pineapple", "rice", "rum", "strawberries", "vanilla"],
        "Dandelion Greens": ["bacon", "cheese", "garlic", "lemon", "mustard","olive oil", "onions","vinegar"],
        "Dates": ["almonds", "apricots", "bacon", "brandy", "caramel", "chocolate", "cinnamon", "cream", "cream cheese", "ginger", "nuts", "orange", "pecans", "rum", "vanilla", "walnuts"],
        "Duck": ["anchovies", "apples", "apricots", "Armangnac", "artichokes", "basil", "blackberries", "blood oranges", "bourbon", "brandy", "cabbage", "Calvados", "cherries", "chiles", "chocolate", "cider", "cloves", "Cognac", "Cointreau", "coriander", "corn", "cranberries", "currants", "curry", "duck livers", "figs", "garlic", "gin", "ginger", "Grand Marnier", "hoisin ssauce", "honey", "juniper berries", "kumquats", "lemon", "lentils", "mangoes", "mint", "molasses", "mushrooms", "mustard", "nutmeg", "olive oil", "olives", "onions", "oranges", "paprika", "parsley", "peaches", "pears", "peas", "pepper", "peppers", "pineapple", "pistachios", "plums", "plum sauce", "pomegranate", "port", "prunes", "quinces", "rhubarb", "rice", "rosemary", "sage", "sauerkraut", "scallions", "shallots", "sherry", "soy sauce", "spinach", "star anise", "stuffing", "tarragon", "thyme", "tomatoes", "turnips", "vinegar", "walnuts", "wine"],
        "Eels": ["aioli", "anchovies", "bacon", "bay leaves", "brandy", "crayfish", "cream", "dill", "garlic", "leeks", "lemon", "mushrooms", "nutmeg", "olive oil", "onions", "parsley", "pepper", "prunes", "raisins", "shallots", "soy sauce", "tomato sauce", "vinegar", "wine"],
        "Eggplant": ["aioli", "anchovies", "bacon", "basil", "bechamel", "bread crumbs", "capers", "goat cheese", "mozzarella cheese", "parmesan cheese", "ricotta cheese", "chervil", "cream", "cumin", "garlic", "ham", "lamb", "lemon", "mint", "mushrooms", "olive oil", "onions", "oregano", "paprika", "parsley", "peppers", "pest", "pine nuts", "rice", "rosemary", "salt", "shallots", "shrimp", "soy", "tarragon", "thyme", "tomatoes", "vinegar", "walnuts", "yogurt", "zucchini"],
        "Eggs": ["anchovies", "asparagus", "bacon", "bread", "butter", "capers", "caviar", "cheese", "chicken livers", "chives", "crab", "cream", "croutons", "fines herbs", "ham", "herbs", "hollandaise sauce", "morels", "mushrooms", "onions", "parmesan", "parsley", "peppers", "potatoes", "ratatouille", "salt", "scallions" , "shallots", "shrimp", "smaoke salmon", "sorrel", "spinach", "tomato", "truffles", "watercress"],
        "Endive": ["apples", "bacon", "beans", "beets", "blue cheese", "bread crumbs", "butter", "cheese", "cream", "figs", "ham", "kumquats", "lemon", "mornay sauce", "mushrooms", "orange", "pears", "roquefort", "scallops", "smoked fish", "sugar", "tangerines", "thyme", "vinaigrette", "walnuts", "watercress"],
        "Escarole": ["apples", "bacon", "capers", "cheese", "chiles", "currants", "eggs", "garlic", "olive oil", "olives", "onions", "vinegar", "walnuts"],
        "Fava Beans": ["bacon", "butter", "cilantro", "cream", "garlic", "ham", "leeks", "lemon", "mushrooms", "olive oil", "pancetta", "parsley", "Pecorino cheese", "rosemary", "sage", "salt", "savory", "spinach", "thyme", "vinaigrette"],
        "Fennel": ["butter", "celery root", "cheese", "chestnuts", "coriander", "cream", "fruit", "garlic", "hearts of palm", "lemon", "mushroom", "olive oil", "olives", "onions", "oranges", "pancetta", "parmesan", "peppers", "Pernod", "potatoes", "sherry", "thyme", "tomatoes", "truffles", "vinaigrette"],
        "Figs": ["almonds", "anise", "brown sugar", "caramel", "cheese", "chocolate", "cinnamon", "basil", "citrus peel", "coconut", "Cointreau", "cornmeal cream", "cream cheese", "creme anglaise", "creme fraiche", "ginger", "honey", "lavender", "lemon", "marsala", "mint", "molasses", "nuts", "orange", "peaches", "pears", "black pepper", "port wine", "praline", "prosciutto", "quince", "raspberries", "rosemary", "sherry", "sour cream", "strawberries", "thyme", "vanilla", "walnuts", "red wine"],
        "Fish": ["almonds", "anchovies", "basil", "butter", "champagne", "cider", "cilantro", "coriander", "cream", "cucumber", "curry", "fennel", "gin", "guava", "horseradish", "kiwi", "leeks", "lemon", "lime", "mace", "marjoram", "mint", "mornay sauce", "mushrooms", "mustard", "nutmeg", "oranges", "oysters", "rosemary", "saffron", "shellfish", "tarragon", "thyme", "tomatoes", "vermouth", "vodka", "white wine"],
        "Flounder": ["butter", "cognac", "lemon", "mushrooms", "mustard"],
        "Foie Gras": ["allspice", "apples", "artichoke hearts", "blood oranges", "brandy", "cabbage", "celery roots", "cherries", "cinnamon", "cloves", "Cognac", "currants", "custard", "daikon", "garlic", "grains", "grapes", "greens", "lemon", "lobster", "Maderia", "mushrooms", "nutmeg", "nuts", "onions", "peaches", "pepper", "pistachios", "polenta", "pomegranates", "port wine", "qinces", "raisins", "salt", "shallots", "star anise", "tarragon", "truffles", "turnips", "vinegar", "walnuts", "wine"],
        "Grapefruit": ["bananas", "brussels sprouts", "Campari", "cashews", "champagne", "cheese", "chicory", "cabbage", "citrus fruits", "Cointreau", "coriander", "fish", "gin", "Grand Marnier", "honey", "melon", "mint", "orange", "pinapple", "pomegrantate", "raspberries", "rosemary", "rum", "shellfish", "sherry", "strawberries", "sugar", "vodka" ],
        "Grapes": ["brandy", "brown sugar", "cheese", "lemon", "melon", "mint", "raspberries", "sour cream", "strawberries", "walnuts", "wine" ],
        "Greens": ["bacon", "butter", "cream", "garlic", "ham", "lemon", "mint", "mushrooms", "mustard", "onions", "pancetta", "black pepper", "sausage", "soy", "vinegar", "walnuts"],
        "Green Beans": ["almonds", "anchovies", "bacon", "basil", "bechamel sauce", "chives", "cream", "garlic", "lemon", "mint", "mushrooms", "mustard", "nutmeg", "nuts", "olive oil", "onions", "oregano", "parmesan cheese", "parsley", "pimentos", "rosemary", "savory", "sour cream", "tomatoes", "vinegar", "walnuts", "worcestershire"],
        "Guavas": ["bananas", "cinnamon", "cloves", "cream", "cream cheese", "fish", "ginger", "honey", "lemon", "lime", "mangoes", "nutmeg", "papayas", "pears", "pineapple", "sugar", "vanilla", "wine"],
        "Halibut": ["anchovies", "bacon", "basil", "butter", "cabbage", "chives", "cucumbers", "fennel", "garlic", "horseradish", "leeks", "lemon", "lime", "mangoes", "mushrooms", "mustard seeds", "onions", "parsley", "potatoes", "rosemary", "saffron", "scallions", "shallots", "shrimp", "tarragon", "thyme", "tomatoes", "vinegar", "white wine", "zucchini"],
        "Ham": ["apples", "barbecue sauce", "basil", "bay leaves", "bourbon", "bread crumbs", "brown sugar", "champagne", "cheese", "cherries", "cider", "cloves", "cola", "cranberries", "cream", "figs", "garlic", "honey", "horseradish", "juniper berries", "lemon", "Maderia", "mushrooms", "mustard", "onions", "oranges", "oregano", "paprika", "parsley", "peaches", "pinapple", "port", "raisins", "rosemary", "sherry", "sour cream", "sweet potatoes", "thyme", "tomatoes", "truffles", "vermouth", "wine"],
        "Hamburger": ["cheddar cheese", "cheese", "chili sauce", "garlic", "ketchup", "mushrooms", "mustard", "onions", "shallots", "tomato sauce", "worcestershire"],
        "Honeydew": ["ginger", "lemon", "lime"],
        "Ice Cream": ["apples", "apricots", "bananas", "buttermilk", "Camembert", "caramel", "cherries", "chocolate", "coffee", "cream" , "ginger", "honey", "maple syrup", "mangoes", "nuts", "oranges", "passion fruit", "peaches", "persimmons", "pistachios", "praline", "raspberries", "rum", "strawberries", "vanilla", "walnuts" ],
        "Jicama": ["cayenne", "chiles", "citrus", "cucumbers", "lime", "mangoes", "oranges", "salt", "vinaigrette"],
        "Kale": ["bacon", "cheese", "cream", "garlic", "lemon", "olive oil", "onions", "potatoes"],
        "Kiwi": ["apples", "bananas", "cucumbers", "honey", "lemon", "lime", "nuts", "oranges", "passion fruit", "proscuitto", "strawberries"],
        "Kumquats": ["apples", "creme anglaise", "gin", "pineapples", "rum", "vanilla", "vodka"],
        "Lamb": ["almonds", "anchovies", "aniseed", "apples", "apricots", "artichoke hearts", "bacon", "basil", "bay leaves", "beans", "blueberries", "bread crumbs", "capers", "cardamom", "cayenne", "cheese", "cherries", "chestnuts", "chiles", "chives", "cilantro", "cinnamon", "cloves", "couscous", "crab", "cream", "cumin", "currants", "curry", "daikon", "dill", "eggplant", "endive", "fennel", "foie gras", "garlic", "ginger", "grapefruit", "gremolata", "hazelnuts", "honey", "juniper berries", "lemon", "Maderia", "mint", "morels", "mushrooms", "mustard", "mustard seeds", "olive oil", "olives", "onions", "oranges", "oregano", "parsley", "pecans", "black pepper", "pine nuts", "pimientos", "pineapple", "plums", "pomegranates", "prunes", "red peppers", "rhubarb", "rice", "rosemary", "rum", "sage", "soy", "star anise", "tamarind", "tarragon", "thyme", "tomatoes", "truffles", "vinaigrette", "vinegar", "walnuts", "wines", "yogurt", "zucchini"],
        "Leeks": ["bacon", "bechamel sauce", "beets", "bread crumbs", "butter", "cheddar cheese", "goat cheese", "cream", "fish", "hollandaise sauce", "lemon", "mustard", "olive oil", "parmesan", "parsley", "peas", "potatoes", "thyme", "tomatoes", "vinaigrette", "red wine"],
        "Lemon": ["almonds", "cardamom", "chocolate", "currants", "honey", "lime", "poppy seeds", "raspberries", "strawberries"],
        "Lentils": ["bacon", "bay leaves", "feta cheese", "goat cheese", "foie gras", "garlic", "ham", "lemon", "mint", "olive oil", "onions", "parsley", "peppers", "pork fat", "prunes", "radishes", "sausages", "scallions", "sorrel", "spinach", "thyme", "tomato sauce", "tomatoes", "vinegar"],
        "Lettuces": ["anchovies", "avocados", "cheese", "egg yolks", "garlic", "lemon", "mayonnaise", "mustard", "hazelnut oil", "olive oil", "peanut oil", "walnut oil", "onions", "pepper", "salt", "salt", "vinaigrette", "vinegar"] ,
        "Lima Beans": ["bacon", "brown sugar", "butter", "cheese", "chiles", "cilantro", "garlic", "onions", "oregano", "rice", "tomatoes"],
        "Lime": ["bananas", "coconut", "lemon", "raspberries", "rum"],
        "Lobster": ["anchovies", "anisette", "apples", "asparagus", "avocados", "bacon", "basil", "bordelaise", "bourbon", "brandy", "bread crumbs", "butter", "caviar", "cayenne", "cheese", "chervil", "chiles", "chives", "cider", "cliantro", "coconut", "Cognac", "coral", "coriander", "corn", "couscous", "cream", "creme fraiche", "curry", "endive", "fennel", "foie gras", "garlic", "ginger", "grapefruit", "hollandaise sauce", "horseradish", "leeks", "lemon", "lemon basil", "lemongrass", "liem", "Maderia", "mayonnaise", "Mornay sauce", "mushrooms", "mustard", "olive oil", "onions", "oranges", "oysters", "paprika", "parsley", "black pepper", "Pernod", "porcini", "port", "Portobello", "quinoa", "rice", "saffron", "seaweed", "shallots", "sherry", "star anise", "tarragon", "thyme", "tomalley", "tomatoes", "black truffles", "vanilla", "vinaigrette", "vinegar"] ,
        "Mache": ["anchovies", "beets", "oils" ,"parmesan"],
        "Mangoes": ["almonds", "blackberries", "cloves", "coconut", "fish", "ginger", "lemon", "lime", "papayas", "passion fruit", "pineapples", "raspberries", "rum", "shellfish", "star anise"],
        "Marrow": ["artichoke hearts", "cayenne", "eggs", "lemon"],
        "Mascarpone": ["brandy", "fruit", "mushrooms", "polenta", "sugar"],
        "Melon": ["basil", "berries", "champagne", "chiles", "Cognac", "Cointreau", "cucmber", "ginger", "grapefruit", "Grand Marnier", "honey", "ice cream", "lime", "Madeira", "mint", "nuts", "oranges", "pear", "pepper", "port", "proscuitto", "raspberries", "salt", "sherry", "strawberries", "vanilla", "wine"],
        "Morels": ["asparagus", "bread crumbs", "butter", "chervil", "chicken", "chives", "cream", "custard", "eggs", "garlic", "lemon", "onions", "parmesan cheese", "parsley", "peas", "pepper", "potatoes", "poultry", "rosemary", "slat", "scallops", "shallots", "sour cream", "tarragon", "tomatoes", "truffles", "watercress"],
        "Mushrooms": ["almonds", "anchovies", "bacon", "barley", "basil", "bread crumbs", "butter", "caraway seeds", "cayenne", "cheese", "chervil", "chives", "coriander", "cream", "creme fraiche", "dill", "eggplants", "eggs", "fish", "garlic", "grapes", "gremolata", "ham", "lemon", "Madeira", "marjoram", "marrow", "mascarpone", "mint", "Mornay sauce", "mustard", "nutmeg", "nuts", "olive oil", "onions", "oranges", "oregano", "oyster sauce", "pancetta", "paprika", "parsley", "pasta", "peas", "black pepper", "pineapple", "pistachios", "potatoes", "rosemary", "sausages", "shallots", "shellfish", "sherry", "sorrel", "sour cream", "spinach", "stock", "tarragon", "thyme", "tomatoes", "vinegar", "walnut oil", "walnuts", "wine" ],
        "Mussles": ["aioli", "anchovies", "aniseed", "bacon", "basil", "bay leaves", "beans", "bread crumbs", "butter", "cayenne", "chervil", "chives", "cilantro", "Cognac", "cream", "curry", "fennel", "garlic", "leeks", "lemon", "lime", "mayonnaise", "mushrooms", "olive oil", "onions", "orange", "pancetta", "parsley", "black pepper", "Pernod", "pesto", "rice", "saffron", "shallots", "snails", "spinach", "thyme", "tomatoes", "vinaigrette", "vinegar", "wine"],
        "Nectarines":["almonds", "berries", "blackberries", "blueberries", "caramel", "champagne", "cherries", "cinnamon", "figs", "ginger", "nuts", "orange", "peaches", "black pepper", "raspberries", "vanilla"],
        "Okra": ["basil", "butter", "garlic", "hollandaise sauce", "lemon", "onions", "parsley", "black pepper", "peppers", "tomatoes", "vinaigrette"],
        "Onions": ["apples", "bacon", "garlic", "hollandaise sauce", "cheese sauce", "cinnamon", "cloves", "cream", "mushrooms", "nutmeg", "paprika", "parmesan cheese", "parsley", "black peper", "raisins", "salt", "sherry", "sorrel", "thyme", "tomatoe sauce", "vinegar", "worcestershire"],
        "Oranges": ["Armangnac", "basil", "brandy", "cardamom", "chipotle pepper", "chocolate", "cinnamon", "coconut", "ginger", "Grand Marnier", "mangoes", "olives", "pecans", "sherry", "strawberries", "vanilla"],
        "Oysters": ["beer", "allspice", "anchovies", "artichokes", "bacon", "bay leaves", "buerre blanc", "bread", "caviar", "champagne", "chiles", "chives", "cilantro", "cream", "cucumbers", "curry", "eggs", "fennel", "foie gras", "garlic", "ginger", "horseradish", "ketchup", "leeks", "lemon", "lime", "mace", "marjoram", "mignonette sauce", "mint", "mustard", "nutmeg", "onions", "pancetta", "paprika", "parmesan cheese" , "parsley", "black pepper", "Pernod", "potatoes", "saffron", "sauerkraut", "scallions", "sea urchin", "shallots", "sherry", "shrimp", "snails", "spinach", "tabasco", "thyme", "vinegar", "wine", "worcestershire"],
        "Papayas": ["avocados", "cayenne", "chicken", "chiles", "conocut cream", "coriander", "cumin", "ginger", "grapefruit", "lemon", "lime", "mangoes", "oranges", "Parma ham", "passion fruit", "peaches", "pineapple", "port", "strawberries", "sugar", "vanilla"],
        "Parsnips": ["almonds", "butter", "chives", "cinnamon", "curry", "garlic", "hazelnuts", "lemon", "Madeira", "nutmeg", "parsley", "black pepper", "potatoes", "sorrel", "tarragon", "walnuts"],
        "Passion Fruit": ["champange", "chocolate", "coconut", "kiwi", "orange", "papaya"],
        "Pasta": ["basil", "beans", "butter", "cheese", "chiles", "cream ", "garlic", "herbs", "lobster", "mascarpone", "mushrooms", "olive oil", "pancetta", "black pepper", "pesto", "pine nuts", "potatoes", "ricotta", "romano cheese", "tomatoes", "truffles" ],
        "Pea Pods": ["almonds", "butter", "chicken", "mushrooms", "peanuts", "sage"],
        "Peaches": ["almonds", "apricots", "basil", "berries", "bourbon", "brandy", "brown sugar", "Calvados", "caramel", "champange", "cherries", "cinnamon", "cloves", "coconut", "Cognac", "Cointreau", "cream", "currants", "Framboise", "ginger", "Grand Marnier", "hazelnuts", "honey", "lemon", "lime", "Maderia", "maple syrup", "Marsala", "oranges", "pecans", "plums", "port", "praline", "raspberries", "rum", "sherry", "sour cream", "strawberries", "sugar", "vanilla", "wine"],
        "Pears": ["almonds", "anise", "Armangnac", "Beaujolais", "blackberries", "bourbon", "brandy", "brown sugar", "Calvados", "caramel", "Cassis", "cheese", "chocolate", "cinnamon", "cloves", "Cognac", "cream", "creme anglaise", "creame fraiche", "currants", "figs", "ginger", "Grand Marnier", "grappa", "hazelnuts", "honey", "ice cream", "lemon", "lingo berries", "mace", "maple syrup", "Marsala", "Muscat", "nutmeg", "nuts", "oranges", "pecans", "black pepper", "pineapple", "prunes", "quinces", "raisins", "raspberries", "Riesling", "spinach", "star anise", "vanilla", "vinegar", "walnuts", "wine", "zabaione"],
        "Peas": ["almonds", "artichokes", "bacon", "butter", "carrrots", "chervil", "chives", "cream", "fennel", "garlic", "ham", "leeks", "lemon", "lettuce", "mint", "mushrooms", "nutmeg", "onions", "parsley", "proscuitto", "rice", "risotto", "rosemary", "sage", "shallots", "sugar", "vinegar"],
        "Pecans": ["bourbon", "brown sugar", "butterscotch", "caramel", "chocolate", "corn syrup", "molasses", "oranges", "rum"],
        "Bell Peppers": ["anchovies", "basil", "chiles", "coriander", "corn", "garlic", "lemon", "meat", "olive oil", "onions", "rice", "tomatoes", "vinegar"],
        "Persimmons": ["brandy", "brown sugar", "caramel", "cinnamon", "cloves", "cream", "custard", "ginger", "grapefruit", "honey", "nutmeg", "pecans", "pork", "sweet potatoes", "vanilla", "yams"],
        "Pheasant": ["apples", "bacon", "brandy", "cabbage", "Calvados", "chestnuts", "chicory", "chiles", "cider", "cream", "creme fraiche", "endive", "foie gras", "garlic", "horseradish", "juniper berries", "lemon", "Madeira", "Marsala", "mushrooms", "olives", "onions", "orange", "oysters", "pecans", "pepper", "pomegranates", "port", "rice", "sage", "sauerkraut", "sausage", "shallots", "sour cream", "tangerines", "thyme", "truffles", "vinegar", "walnuts", "whiskey", "wine"],
        "Pineapple": ["apricots", "avocados", "bacon", "bananas", "brandy", "coconut", "cucumbers", "grapefruits", "hazelnuts", "liquors", "lime", "mangoes", "melon", "mint", "oranges", "papayas", "raspberries", "rum", "strawberries", "sugar", "vanilla"],
        "Plantains": ["bacon", "beans", "cinnamon", "nuts", "pineapples", "rum", "sour cream" ],
        "Plums": ["almonds", "apricots", "bananas", "brandy", "brown sugar", "caramel", "cherries", "cinnamon", "custard", "fruits", "ginger", "grapefruit", "honey", "lemon", "nectarines", "nuts", "oranges", "peaches", "rhubarb", "vanilla", "walnuts", "wine"],
        "Polenta": ["buttter", "cheese", "escarole", "garlic", "mascarpone", "milk", "mushrooms", "pepper", "tomato sauce"],
        "Pomegrantes": ["bananas", "blod oranges", "chocolate", "cream cheese", "grapefruit", "yogurt"],
        "Porcinis": ["butter", "garlic", "Marsala", "olive oil", "parsley", "sage", "sherry", "thyme", "truffles"],
        "Pork": ["apples", "apricots", "bay leaves", "beans", "beer", "brandy", "cabbage", "Calvados", "cherries", "clams", "Cognac", "coriander", "cream", "cumin", "fennel", "fruit", "garlic", "ginger", "hoisin sauce", "honey", "juniper berries", "lemon", "lime", "Marsala", "molasses", "mustard", "onions", "orange", "parsley", "black pepper", "pineapple", "plum sauce", "plums", "prunes", "quinces", "rosemary", "sage", "sauerkraut", "soy sauce", "star anise", "tarragon", "thyme", "vinegar", "walnuts", "whiskey", "wine"],
        "Potatoes": ["anchovies", "bacon", "basil", "butter", "caviar", "cayenne", "celery root", "chard", "cheese", "chervil", "chicory", "chives", "cream", "creme fraiche", "dill", "fennel", "fenugreek", "garlic", "ham", "horseradish", "juniper berries", "kale", "leeks", "lemon thyme", "mint", "mushrooms", "mustard", "nutmeg", "olive oil", "olives", "onions", "paprika", "parsley", "pepper" , "pork", "smoked salmon", "sorrel", "sour cream", "squash", "sweet potatoes", "thyme", "truffles", "turnips"],
        "Prosciutto": ["beans", "bread", "butter", "figs", "kiwi", "melons", "papayas", "peaches", "pears"],
        "Prunes": ["almonds", "apricots", "Armangnac", "brandy", "chestnuts", "cinnamon", "cream", "currants", "lemon", "nuts", "oranges", "pears", "port", "rum", "sherry", "sugar", "vinegar", "walnuts", "wine"],
        "Pumpkin": ["apples", "bacon", "bourbon", "brown sugar", "butter", "caramel", "cinnamon", "cloves", "coconut", "Cognac", "cream", "duck", "garlic", "ginger", "honey", "leeks", "mace", "maple syrup", "mint", "molasses", "mushrooms", "nutmeg", "nuts", "olive oil", "onions", "pecans", "black pepper", "pumpkin seeds", "rum", "sage", "sherry", "sour cream", "sugar", "thyme", "vanilla", "vinegar", "walnuts", "yogurt"],
        "Quail": ["anchovies", "apples", "bacon", "basil", "bay leaves", "beets", "chiles", "cider", "Cognac", "cranberries", "currants", "curry", "figs", "foie gras", "garlic", "gin", "ginger", "grapes", "honey", "juniper berries", "leeks", "lemon", "lime", "maple syrup", "molasses", "mushrooms", "mustard", "onions", "orange", "pancetta", "parsley", "pears", "pecans", "pepper", "persimmons", "pine nuts", "pineapple", "port wine", "potatoes", "prunes", "quail eggs", "quinces", "risotto", "sage", "scallions", "shallots", "thyme", "truffles", "watercress", "white wine", "worcestershire"],
        "Quinces": ["apples",  "brown sugar", "butter", "Cognac", "cream", "foie gras", "honey", "lemon", "nuts", "pears", "raspberries", "vanilla" ],
        "Rabbit": ["almonds", "apricots", "bacon", "basil", "bay leaves", "beer", "brandy", "bread crumbs", "carrots", "cherries", "chervil", "chives", "chocolate", "cider", "cloves", "coriander", "cream", "foie gras", "garlic", "grapes", "horseradish", "juniper berries", "lemon", "Marsala", "mole sauce", "mushrooms", "mustard", "onions", "oranges", "parsley", "pistachios", "prunes", "rosemary", "saffron", "sage", "shallots", "sour cream", "spinach", "tarragon", "thyme", "tomatoes", "vinegar", "walnuts", "wine"],
        "Radicchio": ["anchovies", "bacon", "buttter", "cheese", "garlic", "lemon", "olive oil", "pancetta", "vinegar", "watercress"],
        "Radishes": ["chives", "lemon", "oranges", "parsley", "vinegar"],
        "Raspberries": ["almonds", "apricots", "banana", "brandy", "brown sugar", "buttermilk", "caramel", "champange", "chocolate", "Cognac", "cream", "cream cheese", "currants", "fruits", "Grand Marnier", "lemon", "mangoes", "melons", "peaches", "pears", "black pepper", "pineapple", "pistachios", "sour cream", "wine"],
        "Red Snapper": ["ainse", "basil", "bay leaves", "bordelaise sauce", "butter", "capers", "celery", "cilantro", "cloves", "curry", "dill", "fennel", "five spice powder", "garlic", "ginger", "honey", "leeks", "lemon", "lime", "mustard", "olives", "onions", "oranges", "parsley", "black pepper", "peppers", "potatoes", "remesco sauce", "parmesan cheese", "rosemary", "saffron", "scallions", "sesame", "shallots", "tarragon", "thyme", "tomatoes", "vinegar", "vinaigrette", "wine"],
        "Rhubarb": ["apples", "berries", "brandy", "brown sugar", "butter", "cinnamon", "cream", "fruit", "ginger", "oranges", "pepper", "plums", "sour cream", "sugar"],
        "Rice": ["almonds", "butter", "basil", "cardamom", "cherries", "cinnamon", "coconut", "cream", "curry", "custard", "garlic ", "ginger", "hazelnuts", "lemon", "mushrooms", "nutmeg", "nuts", "oranges", "parsley", "pine nuts", "pineapples", "raisins", "saffron", "tomatoes", "yogurt"],
        "Ricotta": ["almonds", "chocolate", "cinnamon", "cloves", "cream cheese", "garlic", "graham crackers", "lemon", "nutmeg", "nuts", "pepper", "pine nuts", "spinach", "sugar", "vanilla"],
        "Risotto": ["artichokes", "asparagus", "crab", "mushrooms", "parmesan cheese", "peas", "saffron", "shallots", "shellfish", "truffles", "veal", "wine"],
        "Romaine": ["anchovies", "cheese", "chives", "garlic", "lemon", "olive oil", "black pepper"],
        "Rutabegas": ["butter", "cream", "ginger", "lemon", "nutmeg", "parsley", "black pepper", "sage", "sour cream", "thyme"],
        "Salmon": ["aioli", "anchovies", "artichokes", "avocados", "bacon", "basil", "beans", "beurre blanc", "bordelaise sauce", "bread crumbs", "capers", "caviar", "champagne", "chervil", "chives", "citrus", "clams", "Cognac", "coriander", "corn", "crab", "cream", "creme fraiche", "cucumbers", "cumin", "curry", "dill", "fennel", "five-spice powder", "garlic", "ginger", "hollandaise sauce", "horseradish", "juniper berries", "leeks", "lemon", "lime", "Maderia", "maple syrup", "mayonnaise", "mint", "mushrooms", "mustard", "olives", "parsley", "black pepper", "peppers", "pomegranates", "raisins", "sesame", "shallots", "shrimp", "snow peas", "sorrel", "spinach", "tarragon", "tomato", "truffles", "vermouth", "vinaigrette", "vinegar", "walnuts", "watercress", "wine", "worcestershire", "zucchini"],
        "Sauerkraut": ["apples", "bacon", "beer", "brown sugar", "caraway seeds", "cream", "dill", "juniper berries", "mushrooms", "onions", "pheasant", "pineapples", "pork", "potatoes", "sauasges", "shallots", "tomatoes", "wine"],
        "Sausages": ["apples", "cabbage", "cider", "grapes", "lentils", "mustard", "onions", "sauerkraut", "tomatoes", "wine"],
        "Scallops": ["almonds", "anise", "asparagus", "avocados", "bacon", "basil", "bay leaves", "brandy", "bread crumbs", "butter", "cabbage", "capers", "carrots", "caviar", "cayenne", "celery", "cheese", "chervil", "chives", "cilantro", "coriander", "crab", "cream", "cucumbers", "curry", "dill", "endive", "fennel", "foie gras", "garlic", "gin", "ginger", "hollandaise sauce", "Jerusalem artichokes", "leeks", "lemon", "lemongrass", "lemon thyme", "lime", "marjoram", "mint", "Mornay sauce", "mushrooms", "mustard", "olive oil", "onions", "oranges", "paprika", "parsley", "black pepper", "peppers", "Pernod", "porcinis", "potatoes", "pumpkin", "rosemary", "saffron", "salsa", "shallots", "sorrel", "soy sauce", "spinach", "tabasco", "tarragon", "thyme", "tomatoes", "truffles", "vanilla", "vermouth", "vinaigrette", "vinegar", "wine"],
        "Sea Bass": ["anchovies", "basil", "bay leaves", "chervil", "chives", "coriander", "cumin", "curry", "fennel", "garlic", "ginger", "lemon", "Maderia", "mushrooms", "nutmeg", "olive oil", "olives", "oranges", "pepper", "peppers", "rosemary", "seaweed", "shallots", "star anise", "tarragon", "thyme", "tomatoes", "truffles", "vinegar"],
        "Seafood": ["aioli", "avocados", "citrus", "currants", "grapefruit", "lemon", "lettuce", "lime", "olive oill", "parsley", "pepper", "pinenuts"],
        "Shitakes": ["butter", "cabbage", "chicken", "eggplant", "fish", "game", "garlic", "olive oil", "parsley", "shallots"],
        "Shrimp": ["allspice", "anchovies", "artichokes", "bacon", "basil", "bay leaves", "beans", "beer", "brandy", "butter", "buttermilk", "carrots", "caviar", "chervil", "chiles", "chives", "cocktail sauce", "coconut","Cognac", "corn", "cream", "cucumbers", "curry", "dill", "eggplant", "garlic", "ginger", "lemon", "lemongrass", "lime", "Maderia", "mangoes", "mayonnaise", "mint", "mushrooms", "mustard", "olive oil", "onions", "oranges", "parsley", "peanuts", "black pepper", "Pernod", "pineapple", "pomegranates", "rice", "rosemary", "saffron", "scallions", "shallots", "soy sauce", "tabasco", "tarragon", "thyme", "tomatoes", "vinaigrette", "vodka", "wine", "worcestershire"],
        "Snap Peas": ["butter", "olive oil", "vinegar"],
        "Snapper": ["bread crumbs", "endive", "ginger", "mustard"],
        "Sole": ["almonds", "anchovies", "bearnaise sauce", "bechamel sauce", "buttter", "capers", "carrots", "cayenne", "champagne", "chives", "coriander", "cream", "garlic", "hollandaise sauce", "leeks", "lemon", "lobster", "Marsala", "mint", "morels", "mushrooms", "mussles", "mustard", "nutmeg", "olive oil", "onions", "oranges", "oysters", "paprika", "parmesan", "parsley", "black pepper", "peppers", "port wine", "scallions", "shallots", "shrimp", "tabasco", "thyme", "tomatoes", "truffles", "vinaigrette", "vinegar", "wine"],
        "Sorrel": ["butter", "celery root", "chard", "chervil", "cream", "creme fraiche", "eggs", "fish", "lentils", "mustard", "olive oil", "black pepper", "potatoes", "spinach", "tarragon"],
        "Spareribs": ["barbecue sauce", "garlic", "honey", "lemon", "pepper", "plum sauce", "rosemary", "sauerkraut", "soy sauce", "wine", "vinegar"],
        "Spinach": ["anchovies", "brains", "butter", "cardamom", "carrots", "cheese", "chiles", "chives", "cream", "cumin", "curry", "eggs", "fish", "garlic", "ginger", "ham", "hollandaise sauce", "horseradish", "leeks", "lemon", "lemongrass", "mint", "mushrooms", "mustard", "nutmeg", "nuts", "olive oil", "olives", "onions", "oranges", "black pepper", "peppers", "raisins", "sorrel", "sour cream", "soy", "sugar", "tarragon", "tomatoes", "vinegar", "yogurt"],
        "Squab": ["apricots", "bacon", "basil", "beer", "brandy", "butter", "cabbage", "cherries", "chestnuts", "chives", "chocolate", "cider", "Cognac", "cranberries", "cream", "cumin", "currants", "eggplant", "figs", "foie gras", "garlic", "grapes", "huckleberries", "juniper berries", "lemon", "lime", "mushrooms", "olive oil", "olives", "onions", "oranges", "onions", "oranges", "paprika", "parsley", "peaches", "peas", "black pepper", "raspberries", "rhubarb", "rice", "rosemary", "sage", "shallots", "sour cream", "soy", "stuffing", "tarragon", "thyme", "vinegar", "truffles", "wine"] ,
        "Acorn Squash": ["bacon", "brown sugar", "butter", "garlic", "honey", "maple syrup", "nutmeg", "parmesan", "black pepper", "sage"],
        "Butternut Squash": ["ancho chiles", "apples", "butter", "celery root", "cheddar cheese", "chestnuts","chorizo", "cinnamon", "curry", "nuts", "oranges","parmesan","pears", "pecans", "rosemary", "sage", "sherry"],
        "Spaghetti Squash": ["butter", "cream", "nutmeg", "parmesan", "black pepper", "tomato sauce"],
        "Squash": ["bacon","brown sugar", "butter", "cheese", "chiles", "cinnamon", "cream", "garlic", "ginger", "leeks", "maple syrup", "mint", "nutmeg", "nuts", "olive oil", "onions", "oranges", "parsley", "pineapples", "potatoes", "raisins", "sage", "sherry", "thyme", "truffles", "vanilla"],
        "Squid": ["anchovies", "basil", "bay leaves", "bread crumbs", "cilantro", "garlic", "ginger", "lemon", "lime", "mayonnaise", "mint", "olive oil", "onions", "parsley", "rosemary", "salsa", "squid ink", "tomatoes", "vinaigrette", "wine"],
        "Steak": ["avocados", "basil", "bearnaise sauce", "bourbon", "brandy", "butter", "cayeen", "chives", "Cognac", "coriander", "garlic", "ginger", "horseradish", "juniper berries", "leeks", "lemon", "Madeira", "mushrooms", "mustard", "olive oil", "onions", "parsley", "black pepper", "peppers", "potatoes", "rosemary", "scallions", "shallots", "sherry", "sour cream", "soy", "Stilton cheese", "tomatoes", "truffles", "vinegar", "wine", "whiskey", "worcestershire"],
        "Strawberries": ["almonds", "apricots", "bananas", "basil", "brown sugar", "caramel", "Cassis", "champange", "cinnamon", "clotted cream", "coconut", "Cognac", "Cointreau", "cream", "cream cheese", "creme fraiche", "currant", "figs", "Grand Marnier", "grapefruits", "guavas", "kiwi", "lemon", "lime", "maple syrup", "mascarpone", "nuts", "oranges", "passion fruit", "peaches", "black pepper", "pineapple", "port", "raspberries", "rhubarb" , "sambuca", "sherry", "sour cream", "sugar", "vanilla", "balsamic vinegar", "violets", "wine", "yogurt", "zabaione" ],
        "Stuffing": ["apples", "bacon", "Brazil nuts", "bread crumbs", "carrots", "celery", "chestnuts", "cornbread", "garlic", "bourbon", "Cognac", "whiskey", "liver", "mushrooms", "nutmeg", "onions", "oysters", "pancetta", "parsley", "pecans", "prunes", "rice", "rosemary", "sage", "sausages", "shallots", "tarragon", "thyme", "walnuts"],
        "Sweetbreads": ["apples", "brandy", "bread crumbs", "butter", "capers", "carrots", "cherries", "chervil", "citrus", "clove", "corn", "cream", "creme fraiche", "curry", "eggs", "garlic", "hazelnuts", "hollandaise sauce", "lemon", "Madeira", "Marsala", "morels", "mushrooms", "mustard", "onions", "oysters", "parmesan cheese", "parsley", "peas", "peppers", "port", "shallots", "sherry", "spinach", "tarragon", "thyme", "tomatoes", "truffles", "walnut oil", "watercress", "wine"],
        "Swiss Chard": ["chiles", "garlic", "lemon", "tarragon", "tomatoes", "vinegar"],
        "Swordfish": ["basil", "Beaujolais", "beet juice", "butter", "capers", "caviar", "chanterelles", "chives", "coconut", "coriander", "cream", "curry", "ginger", "grapefruit", "lemon", "mustard", "olive oil", "parsley", "pineapples", "rosemary", "tarragon", "tomatoes", "vinaigrette", "balsamic vinegar", "wine"],
        "Tomatoes": ["anchovies", "arugula", "basil", "bread crumbs", "champagne", "feta cheese", "goat cheese", "mozzarella cheese", "parmesan cheese", "chiles", "chives", "cucumbers", "eggs", "garlic", "lemon", "marjoram", "mint", "mushrooms", "olive oil", "olives", "onions", "oregano", "parsley", "pasta", "black pepper", "peppers", "saffron", "seafood", "shallots", "tarragon", "thyme", "vinegar"  ],
        "Tongue": ["anchovies", "capers", "cherries", "chervil", "chives", "garlic", "horseradish", "lemon", "mushrooms", "mustard", "olive oil", "parsley", "black pepper", "port", "rosemary", "tarragon", "thyme", "tomatoes", "vinegar"],
        "Trout": ["almonds", "anchovies", "bacon", "beans", "butter", "capers", "chervil", "chiles", "chives", "cream", "garlic", "horseradish", "lemon", "mushrooms", "parsley", "pears", "black pepper", "Pernod", "port", "scallions", "sorrel", "tabasco", "tomatoes", "vinegar", "walnuts", "wine"],
        "Truffles": ["butter", "champagne", "chicken", "Cognac", "cream", "eggs", "foie gras", "garlic", "ham", "leeks", "Madeira", "meats", "morels", "onions", "parmesan cheese", "pasta", "pepper", "port", "potatoes", "poultry fat", "risotto", "sweetbreads"],
        "Black Truffles": ["chicken", "eggs", "fish", "foie gras", "pate", "potatoes", "poultry", "turkey", "veal", "wine"],
        "White Truffles": ["butter", "cheese", "eggs", "pasta", "risotto", "salads"] ,
        "Tuna": ["aioli", "anchovies", "artichokes", "avocados", "bacon", "bay leaves", "beans", "beets", "capers", "carrots", "caviar", "chives", "cilantro", "daikon", "dill", "garlic", "ginger", "leek", "lemon", "lemongrass", "mayonnaise", "mint", "mushrooms", "olive oil", "onions", "parsley", "black pepper", "peppers", "pineapple", "pototoes", "saffron", "scallions", "seaweed", "sesame", "soy sauce", "teriyaki sauce", "thyme", "tomatoe sauce", "tomatoes", "vinaigrette", "vinegar", "wasabi", "wine"],
        "Turkey": ["celery", "celery root", "cheese", "chestnuts", "chocolate", "ham", "lemon", "Madeira", "maple syrup", "Marsala", "mole sauce", "mushrooms", "parsley", "prunes", "raspberries", "sage", "stuffing", "tarragon", "thyme", "truffles", "vinegar", "white wine" ],
        "Turnips": ["apples", "bacon", "butter", "carrots", "cheese", "chives", "cider", "cinnamon", "cream", "fat", "garlic", "lemon", "maple syrup", "mushrooms", "mustard", "onions", "paprika", "parsley", "potatoes", "salt", "sherry", "sugar", "sweet pototaotes", "tarragon", "thyme", "vinaigrette"],
        "Veal": ["anchovies", "apples", "artichokes", "arugula", "bacon", "basil", "bay leaves", "bread crumbs", "butter", "capers", "carrots", "cheese", "chervil", "cider", "cloves", "corn", "cream", "dill", "endive", "foie gras", "garlic", "ginger", "grapefruit", "hame", "leeks", "lemon", "lime", "Madeira", "Marsala", "morels", "Mornay sauce", "mushrooms", "mustard", "olive oil", "onions", "paprika", "Parma ham", "parsley", "black pepper", "peppers", "pistachios", "potatoes", "rosemary" , "sage", "salmon", "shallots", "sorrel", "sour cream", "spinach", "sweetbreads", "tapenade", "tarragon", "thyme", "tomatoes", "truffles", "tuna", "verbena", "vermouth"],
        "Venison": ["apples", "bacon", "bananas", "barley", "bay leaf", "bearnaise sauce", "brandy", "cherries", "chestnuts", "chiles", "cider", "coriander seeds", "cream", "currants", "garlic", "goat cheese", "horseradish", "huckleberries", "juniper berreis", "Madeira", "marjoram", "mushrooms", "mustard", "onions", "oranges", "parsnips", "pears", "black pepper", "pomegranates", "port", "prickly pears", "prunes", "rosemary", "sweet potatoes", "tarragon", "thyme", "vinegar", "wine"],
        "Walnuts": ["caramel", "cheese", "fish", "mushrooms", "pork", "port", "raisins", "salads", "sherry", "zucchini"],
        "Watercress": ["beets", "chicory", "eggs", "endive", "mustard", "oranges", "oregano", "parsley", "thyme", "vinaigrette", "walnuts"],
        "Yams": ["apricots", "butter", "persimmons", "maple"],
        "Yogurt": ["apples", "bananas", "blueberries", "carrots", "coconuts", "cucumbers", "granola", "honey", "mint", "nuts", "oats", "onion", "peaches", "radishes", "raspberries", "strawberries", "watercress"],
        "White Beans": ["bacon", "bay leaf", "chervil", "chives", "cream", "garlic", "maple syrup", "molasses", "olive oil", "onions", "parsley", "rosemary", "rum", "sage", "shallots", "red wine"],
        "White Chocolate": ["bananas", "berries", "blackberries", "boysenberries", "cherries", "coconuts", "hazelnuts", "oranges", "raspberries", "rum", "violets"],
        "Zucchini": ["anchovies", "basil", "bread crumbs", "butter", "cayenne","cheese", "cilantro", "cinnamon", "cloves", "cream", "dill", "eggplant", "garlic", "hazelnuts", "lemon", "marjoram", "mint", "mushrooms", "olive oil", "onions", "oregano", "parsley", "pesto", "rosemary", "sage", "salmon", "tarragon", "thyme", "tomatoes", "vinegar", "walnuts"]
      };
      if(data[this.ingredient]){
        console.log(data);
        this.ingredient = data[this.ingredient];
        console.log(data[this.ingredient]);
      }
      // for(key in data){
      //   if(key === ingredient){
      //     console.log(data[key]);
      //     return this.ingredient = data[key];
      //   }
      // }
    // })
  }
  }
})
